name: Qrypsis CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  scan:
    name: Run Qrypsis Scanner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
      
      - name: Ensure script is executable
        run: chmod +x run_scan.sh

      - name: Run Qrypsis Scanner
        run: |
          ./run_scan.sh || true

      - name: Upload Compliance Reports
        uses: actions/upload-artifact@v4
        with:
          name: qrypsis-reports
          path: |
            report.md
            report.html
            report.pdf

      - name: Post-scan summary
        run: echo "✅ Qrypsis scan completed. Artifacts uploaded."
